"""Create one platform-specific Envoy release archive."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import tarfile
import tempfile
import zipfile
from datetime import UTC, datetime
from pathlib import Path, PurePosixPath

REPO_ROOT = Path(__file__).resolve().parent.parent


def parseArguments() -> argparse.Namespace:
    """Parse release-packaging arguments.

    Returns:
        Parsed command-line options.

    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", required=True, help="Release version, including any v prefix.")
    parser.add_argument("--target-name", required=True, help="Artifact target label.")
    parser.add_argument("--binary-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, default=REPO_ROOT / "dist")
    parser.add_argument("--windows", action="store_true", help="Package .exe files in a ZIP.")
    return parser.parse_args()


def copyReleaseFiles(
    bundle_root: Path,
    binary_directory: Path,
    version: str,
    windows: bool,
) -> None:
    """Populate a staged, versioned release bundle.

    Args:
        bundle_root: Destination corresponding to ``gt/envoy/<version>``.
        binary_directory: Directory containing the built native CLIs.
        version: Version written to the production bundle marker.
        windows: Whether to package Windows executables and launchers.

    """
    bundle_root.mkdir(parents=True)
    shutil.copytree(REPO_ROOT / ".envoy", bundle_root / ".envoy")
    shutil.copy2(REPO_ROOT / "LICENSE", bundle_root / "LICENSE")
    shutil.copy2(REPO_ROOT / "README.md", bundle_root / "README.md")
    marker_data = {
        "bndlid": "gt:envoy",
        "name": "envoy",
        "version": version,
        "published": datetime.now(UTC).isoformat(),
    }
    (bundle_root / ".bundle").write_text(
        json.dumps(marker_data, indent=2) + "\n",
        encoding="utf-8",
    )

    bin_directory = bundle_root / "bin"
    bin_directory.mkdir()
    suffix = ".exe" if windows else ""
    for executable_name in ("envoy",):
        source = binary_directory / f"{executable_name}{suffix}"
        if not source.is_file():
            raise FileNotFoundError(f"Native executable not found: {source}")
        destination = bin_directory / f"{executable_name}{suffix}"
        shutil.copy2(source, destination)
        if not windows:
            destination.chmod(destination.stat().st_mode | 0o755)

    alias_name = "en.bat" if windows else "en"
    alias_source = REPO_ROOT / "bin" / alias_name
    alias_destination = bin_directory / alias_name
    shutil.copy2(alias_source, alias_destination)
    if not windows:
        alias_destination.chmod(alias_destination.stat().st_mode | 0o755)


def writeArchive(
    staging_directory: Path,
    output_directory: Path,
    version: str,
    target_name: str,
    windows: bool,
) -> Path:
    """Write the staged tree as ZIP or compressed tar.

    Args:
        staging_directory: Directory containing the ``gt`` archive root.
        output_directory: Destination for the completed archive.
        version: Release version used in the filename.
        target_name: Platform label used in the filename.
        windows: Whether to emit ZIP instead of ``tar.gz``.

    Returns:
        Path to the completed archive.

    """
    output_directory.mkdir(parents=True, exist_ok=True)
    base_name = f"envoy-{version}-{target_name}"
    if windows:
        archive_path = output_directory / f"{base_name}.zip"
        with zipfile.ZipFile(archive_path, "w", zipfile.ZIP_DEFLATED) as archive:
            for source in sorted(staging_directory.rglob("*")):
                if source.is_file():
                    archive.write(source, source.relative_to(staging_directory).as_posix())
    else:
        archive_path = output_directory / f"{base_name}.tar.gz"
        with tarfile.open(archive_path, "w:gz") as archive:
            archive.add(
                staging_directory / "gt",
                arcname="gt",
                filter=normalizeTarMetadata,
            )

    return archive_path


def normalizeTarMetadata(member: tarfile.TarInfo) -> tarfile.TarInfo:
    """Make Unix archive ownership and permissions host-independent.

    Args:
        member: Archive entry generated by :mod:`tarfile`.

    Returns:
        The normalized archive entry.

    """
    archive_path = PurePosixPath(member.name)
    executable_names = {"en", "envoy"}
    is_executable = archive_path.parent.name == "bin" and archive_path.name in executable_names

    member.uid = 0
    member.gid = 0
    member.uname = "root"
    member.gname = "root"
    if member.isdir() or is_executable:
        member.mode = 0o755
    elif member.isfile():
        member.mode = 0o644
    return member


def main() -> int:
    """Create one release archive.

    Returns:
        Process exit status.

    """
    options = parseArguments()
    binary_directory = options.binary_dir.resolve()
    output_directory = options.output_dir.resolve()

    with tempfile.TemporaryDirectory(prefix="envoy-release-") as temporary_path:
        staging_directory = Path(temporary_path)
        bundle_root = staging_directory / "gt" / "envoy" / options.version
        copyReleaseFiles(bundle_root, binary_directory, options.version, options.windows)
        archive_path = writeArchive(
            staging_directory,
            output_directory,
            options.version,
            options.target_name,
            options.windows,
        )

    print(os.fspath(archive_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
